---
title: 'UIコールバック'
---
After Effects は、推測や OS に直接問い合わせることなく、座標系間で転置し、描画コンテキストに関する OS 固有の情報を取得するためのコールバックを提供します。これらのコールバックを使用してください。これらのコールバックへのポインタは、PF_EventCallbacks で提供されます。これらのルーチンにアクセスするには、AE_EffectUI.h および AE_EffectCB.h のマクロを使用します。

座標系転置コールバックを実装せずに、カスタム UI を利用する機能するプラグインを構築することができます。ただし、ユーザーがレイヤー パネルにズームインしたり、レイヤーを回転したりすると、プラグインの動作がおかしくなります。これらのマクロとコールバックを追加したことで、開発者にユーザー インターフェイスのオーバーヘッドを与えることなく、カスタムユーザーインターフェイスを After Effects UI に簡単に統合できるようになりました。またぜひご利用ください！

これらのマクロは、簡略化するために refcon およびコンテキスト ハンドルをデフォルトに設定します。 refcon は、「extra」という名前のローカル変数があることを前提としています。デフォルトのコンテキストは現在のコンテキストです。これらのデフォルト パラメーターは、PF_EventCallbacks 構造体 (AE_EffectUI.h 内) で定義されます。 PF_EventExtra 構造体を通じてコールバックにアクセスすることで、デフォルトをオーバーライドできます。ヘッダー ファイル内のマクロの変更はお勧めしません (またはサポートしません)。やめてください！

| Function | Purpose |
| --- | --- |
| `layer_to_comp` | Transforms layer panel coordinates to the composition panel coordinates.<br /><br /><pre lang="cpp">PF_Err layer_to_comp (<br/>  void           \*refcon,<br/>  PF_ContextH    context,<br/>  A_long         curr_time,<br/>  A_long         time_scale,<br/>  PF_FixedPoint  \*pt);</pre> |
| `comp_to_layer` | Transforms composition panel coordinates to the layer panel coordinates.<br /><br /><pre lang="cpp">PF_Err comp_to_layer (<br/>  void           \*refcon,<br/>  PF_ContextH    context,<br/>  A_long         curr_time,<br/>  A_long         time_scale,<br/>  PF_FixedPoint  \*pt);</pre> |
| `get_comp2layer_xform` | Returns the matrix used to convert from the composition panel to the layer panel.<br /><br />If `*exists` returns `FALSE`, the matrix cannot be computed because the layer scales to zero.<br /><br /><pre lang="cpp">PF_Err get_comp2layer_xform (<br/>  void            \*refcon,<br/>  PF_ContextH     context,<br/>  A_long          curr_time,<br/>  long            time_scale,<br/>  long            \*exists,<br/>  PF_FloatMatrix  \*comp2layer);</pre> |
| `get_layer2comp_xform` | Returns the transformation matrix used to convert from the layer panel to the composition panel.<br /><br />This always exists.<br /><br /><pre lang="cpp">PF_Err get_layer2comp_xform (<br/>  void            \*refcon,<br/>  PF_ContextH     context,<br/>  A_long          curr_time,<br/>  A_long          time_scale,<br/>  PF_FloatMatrix  \*layer2comp);</pre> |
| `source_to_frame` | Transforms the source coordinates in the current context to screen coordinates.<br /><br />Screen (frame) coordinates are affected by the current zoom level.<br /><br /><pre lang="cpp">PF_Err source_to_frame(<br/>  void           \*refcon,<br/>  PF_ContextH    context,<br/>  PF_FixedPoint  \*pt);</pre> |
| `frame_to_source` | Transforms the screen coordinates identified by `*pt` to the source coordinates of the current context.<br /><br /><pre lang="cpp">PF_Err frame_to_source(<br/>  void           \*refcon,<br/>  PF_ContextH    context,<br/>  PF_FixedPoint  \*pt);</pre> |
| `PF_GET_PLATFORM_DATA` | Retrieves platform-specific data. For plug-ins loaded with localized resource files, `PF_PlatData_RES_FILE_PATH` will point to the external file, not the plug-in file.<br /><br />Use `PF_PlatData_EXE_FILE_PATH` if you want the path of your plug-in.<br /><br />Starting in CS6, use `PF_PlatData_EXE_FILE_PATH_W` and `PF_PlatData_RES_FILE_PATH_W` instead of the old non-wide calls.<br /><br /><pre lang="cpp">PF_Err PF_GET_PLATFORM_DATA (<br/>  PF_PlatDataID  which,<br/>  void           \*ppData);</pre><br /><br />`PF_PlatDataID` can have the following values:<br /><br />- `PF_PlatData_MAIN_WND`<br />- `PF_PlatData_EXE_FILE_PATH_DEPRECATED`<br />- `PF_PlatData_RES_FILE_PATH_DEPRECATED`<br />- `PF_PlatData_RES_REFNUM` // macOS<br />- `PF_PlatData_RES_DLLINSTANCE` // Win<br />- `PF_PlatData_BUNDLE_REF`<br />- `PF_PlatData_EXE_FILE_PATH_W` // new CS6<br />- `PF_PlatData_RES_FILE_PATH_W` // new CS6 |
